language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: HpTHshb0LG5JaksU4FKRtkkMToiKIi4BuMRA+o8ISwqiriOsP+sxWg3r/qgnA3NTrhI5IA4eOeCrZHh3gn6YkeQ4A5AxZFpErBMhNDu6F3R1fJ4QMAbcNSga6TeHLuCkoXQa0oDREXzVv8oHMrW/4mVcHq1gjCU+QGBlF1LUFcYcZPq/Zxc/NtRvwbhtlOCg+RSYZ0idM9EVPIUzaCmNTqsKwkgIulis3DlXesCpladbhJkyLU11NzTBhVPPodYxpjC7Qnc4a0OlvgGPbJVmMCZ1zLS7beFymMKZCt3F51zxsdYivS9wbaDpBjUA6mMoMy20m+96VNqrEgPgn3mvWyMfLZ41vnq4dPLnolhQ6qU4KmkxtzWJY4XuYRLYOzqn9JR06p+UzWKKvEM4BPIFBJ1M7F9xY0d7MLIrkJCT8oCrY5CpWTj9U3xNq2/jykJejEXODx807CKey6j7sQMmpXDxsZW1UT1JDZU1/dUCfkLG3BcxNCiuup8GwDl4jDKdkPKwhiTbbQDwypS/bjVzUNz3E+YngvvhG5BIifqjt7PH2/sbdrnzqy0EzAED7dCG8ojnE8kMURmUDncuqTgm56a+JonZoIMI1fXBlLekHXbjY24Iq0eH1xHJW5XMJxdQbpl6JrOgI5roqwK8UQymXUrDrUUxIgKrD4yy65A1ziM=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-plugin-postcss
